language: java
jdk: openjdk14

services: docker

script:
  - docker build -t message-broker-performance-tests:0.0.1 .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push stefanvassilev/message-broker-performance-tests
