language: java
jdk: openjdk14

services: docker

before_install:
  - docker build -t message-broker-performance-tests:0.0.1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stefanvassilev/message-broker-performance-tests
