# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:8080
          - message-broker-performance-tests:8080